// Geometry Dash Demon List
// Based on pointercrate.com/demonlist
// Custom: Ton 618 = #1, Thinking Space II = #2

const DEMONS = [
  // ── MAIN LIST (1–75) ──────────────────────────────────────
  { rank: 1,   name: "Ton 618",                creator: "Exen",                  list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 2,   name: "Thinking Space II",       creator: "Atomic",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 3,   name: "Amethyst",                creator: "iMist",                 list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 4,   name: "Tidal Wave",              creator: "OniLink",               list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 5,   name: "ORBIT",                   creator: "MindCap",               list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 6,   name: "Nullscapes",              creator: "Kiba",                  list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 7,   name: "Quanteuse processing",    creator: "Renn241",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 8,   name: "BOOBAWAMBA",              creator: "Akunakunn",             list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 9,   name: "Every End",               creator: "MindCap",               list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 10,  name: "Penumbral",               creator: "cherryteam",            list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 11,  name: "Silent clubstep",         creator: "TheRealSailent",        list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 12,  name: "Ashley Wave Trials",      creator: "oddmod",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 13,  name: "andromeda",               creator: "Insxne97",              list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 14,  name: "Subsuming Vortex",        creator: "[TCD] Cursed",          list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 15,  name: "Anathema",                creator: "nikroplays",            list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 16,  name: "Avernus",                 creator: "PockeWindfish",         list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 17,  name: "Acheron",                 creator: "ryamu",                 list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 18,  name: "Spectre",                 creator: "xander",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 19,  name: "Menace",                  creator: "Arraegen",              list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 20,  name: "Abyss of Darkness",       creator: "Exen",                  list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 21,  name: "Defeated Circles",        creator: "GXQ",                   list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 22,  name: "Tunnel of Despair",       creator: "Exen",                  list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 23,  name: "Kyouki",                  creator: "｛出見塩｝",             list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 24,  name: "Based After Based",       creator: "Akunakunn",             list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 25,  name: "Subterminal Point",       creator: "SyQual",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 26,  name: "Slaughterhouse",          creator: "icedcave",              list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 27,  name: "KOCMOC",                  creator: "cherryteam",            list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 28,  name: "The Lightning Rod",       creator: "Lavatrex",              list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 29,  name: "CHIL",                    creator: "McCoco",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 30,  name: "zorin",                   creator: "SnowEye",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 31,  name: "Sakupen Circles",         creator: "[TCD] Diamond",         list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 32,  name: "Deimos",                  creator: "ItsHybrid",             list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 33,  name: "Eyes in the Water",       creator: "hawkyre",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 34,  name: "Voltage",                 creator: "ThePurgatory",          list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 35,  name: "KOSETSU",                 creator: "fwe",                   list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 36,  name: "Through The Gates",       creator: "TeamTheDashers",        list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 37,  name: "Firework",                creator: "[TCD] Trick",           list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 38,  name: "Silentlocked",            creator: "GDSkele",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 39,  name: "NOMAD",                   creator: "ReeseVT",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 40,  name: "poocubed",                creator: "Liisp",                 list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 41,  name: "Snowbound",               creator: "[JUICE] Amplitron",     list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 42,  name: "The Salt Factory",        creator: "[UFA] Nickname09",      list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 43,  name: "CONVULSION",              creator: "stellar",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 44,  name: "BEING HOME",              creator: "Turtl123",              list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 45,  name: "Calibrate",               creator: "[SARK] Bamvie",         list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 46,  name: "MINUSdry",                creator: "CDMusic",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 47,  name: "Saul Goodman",            creator: "Renn241",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 48,  name: "Apocalyptic Trilogy",     creator: "APTeamOfficial",        list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 49,  name: "Sevvend Clubstep",        creator: "cherryteam",            list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 50,  name: "The Hallucination",       creator: "SyQual",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 51,  name: "COMBUSTION",              creator: "[SKWAD] Cersia",        list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 52,  name: "Deadlier Clubstep",       creator: "HeroZombie80",          list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 53,  name: "Stellar Night",           creator: "icedcave",              list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 54,  name: "Edge of Destiny",         creator: "CDMusic",               list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 55,  name: "Solar Flare",             creator: "Linear",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 56,  name: "The Catacombs",           creator: "[SKWAD] Cersia",        list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 57,  name: "LIMBO",                   creator: "MindCap",               list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 58,  name: "Gaggatrondra",            creator: "JCMoon",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 59,  name: "Belladonna",              creator: "cherryteam",            list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 60,  name: "Codependence",            creator: "TCTeam",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 61,  name: "Collapse",                creator: "[COMET] Nexel",         list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 62,  name: "Mayhem",                  creator: "[DL] LordVadercraft",   list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 63,  name: "CHROMACAVE",              creator: "HappyMoby",             list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 64,  name: "The Plunge",              creator: "Dolabill",              list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 65,  name: "Fracture",                creator: "Arrow",                 list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 66,  name: "walter white",            creator: "Renn241",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 67,  name: "Infinite Chaos",          creator: "CairoX",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 68,  name: "BRITNEY NO SCLEARS",      creator: "wabas",                 list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 69,  name: "Operation Evolution",     creator: "Halzion",               list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 70,  name: "Damascus",                creator: "Dzeser",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 71,  name: "Decks Dark",              creator: "[SKG] Madison Yuko",    list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 72,  name: "SARYYX NEVER CLEAR",      creator: "artos",                 list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 73,  name: "The Yangire",             creator: "Dorami",                list: "main",     difficulty: "Extreme Demon", featured: true  },
  { rank: 74,  name: "Climax",                  creator: "HushLC",                list: "main",     difficulty: "Extreme Demon", featured: false },
  { rank: 75,  name: "ORDINARY",                creator: "vit12",                 list: "main",     difficulty: "Extreme Demon", featured: false },

  // ── EXTENDED LIST (76–150) ────────────────────────────────
  { rank: 76,  name: "TrakineS",                creator: "Laranjoo",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 77,  name: "Loops of Fury",           creator: "[TCC] Enfur",           list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 78,  name: "Wavterminal",             creator: "Skyavoxii",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 79,  name: "Sinister Silence",        creator: "Wahffle",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 80,  name: "THE JET ENGINE",          creator: "[TARIQ] Billzer",       list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 81,  name: "Midnight",                creator: "[SKG] Madison Yuko",    list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 82,  name: "Cimmerian Shade",         creator: "spcreat",               list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 83,  name: "PSYCHOPATH",              creator: "DeniPol",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 84,  name: "arcturus",                creator: "Maxfs",                 list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 85,  name: "Diabolic ClubStep",       creator: "Sevant",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 86,  name: "BEELINE",                 creator: "[DOOBY] Galaxxyss",     list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 87,  name: "Sonic Wave Infinity",     creator: "APTeamOfficial",        list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 88,  name: "Tartarus",                creator: "[USSR] Dolphy",         list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 89,  name: "Coalescence",             creator: "[JUICE] Amplitron",     list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 90,  name: "Waterfall",               creator: "cherryteam",            list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 91,  name: "Jigsaw",                  creator: "NekonGames",            list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 92,  name: "Delta",                   creator: "[FaZe] Drakosa",        list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 93,  name: "BPATA MPAKA",             creator: "Inex",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 94,  name: "The Wonder of You",       creator: "HangerLord",            list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 95,  name: "Natural Disaster",        creator: "[OG B] Laysah",         list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 96,  name: "Terminal Rampancy",       creator: "Xyriak",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 97,  name: "Dualist",                 creator: "Syncroned",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 98,  name: "The Golden",              creator: "BoBoBoBoBoBoBo",        list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 99,  name: "Oblivion",                creator: "[DLNW] Dice88",         list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 100, name: "DreamStep",               creator: "Blaster1337",           list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 101, name: "Viprin UFO",              creator: "hawkyre",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 102, name: "NETWORK",                 creator: "Agat3",                 list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 103, name: "Verdant Landscape",       creator: "Nisha",                 list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 104, name: "Levigo",                  creator: "Swib",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 105, name: "UNKNOWN",                 creator: "NineDice",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 106, name: "ATOMIC CANNON Mk III",    creator: "Lieb",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 107, name: "Shukketsu",               creator: "[SKG] Madison Yuko",    list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 108, name: "Checked Steam",           creator: "gruzy",                 list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 109, name: "Critical Heat",           creator: "Zeniux",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 110, name: "WOBBLING MACHINE",        creator: "Smarted",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 111, name: "Crystal Crusher",         creator: "Zeniux",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 112, name: "limbo but uwu ig idk",    creator: "Akunakunn",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 113, name: "Graceful",                creator: "[1319] D A G",          list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 114, name: "paranoia",                creator: "[JUICE] Amplitron",     list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 115, name: "The Paroxysm of Rage",    creator: "Zacanaii",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 116, name: "Blood Echo",              creator: "Farva",                 list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 117, name: "Aerial Gleam",            creator: "Endlevel",              list: "extended", difficulty: "Hard Demon",    featured: true  },
  { rank: 118, name: "DISCONNECT",              creator: "MCres",                 list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 119, name: "VOID",                    creator: "nikoberry",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 120, name: "Starlit Stroll",          creator: "[TCC] Enfur",           list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 121, name: "Henken",                  creator: "PLoLek",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 122, name: "Trueffet",                creator: "SyQual",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 123, name: "azure blast",             creator: "[YAHO] AlbinoSnail",    list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 124, name: "Kenos",                   creator: "npesta",                list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 125, name: "Fragile",                 creator: "Endlevel",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 126, name: "chrome hearts",           creator: "Roadbose",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 127, name: "Starlight Summit",        creator: "[BDAY] hazelmrow",      list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 128, name: "Esfera",                  creator: "SyQual",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 129, name: "Destruction 19",          creator: "bosjoker",              list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 130, name: "in this",                 creator: "enci",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 131, name: "Time Lapse",              creator: "HappyMoby",             list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 132, name: "NEUTRA",                  creator: "Jenkins GD",            list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 133, name: "Dark Dimension",          creator: "ThePurgatory",          list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 134, name: "Swing Swing",             creator: "[COMET] Kaza",          list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 135, name: "Guideless Goobering",     creator: "[TCC] Enfur",           list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 136, name: "Hard Machine",            creator: "Komp",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 137, name: "DISSONANCE",              creator: "[meow] ivyteal",        list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 138, name: "Goober Rage Stage",       creator: "bonscarrot",            list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 139, name: "Crackhead Circles",       creator: "AlrexX",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 140, name: "Zodiac",                  creator: "Bianox",                list: "extended", difficulty: "Extreme Demon", featured: true  },
  { rank: 141, name: "Lotus Flower",            creator: "StarkytheSalad",        list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 142, name: "Scream Machine",          creator: "TMco",                  list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 143, name: "Axinie",                  creator: "[IQB7] SaturMan",       list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 144, name: "Judgement Knights",       creator: "HangerLord",            list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 145, name: "Widestep",                creator: "｛出見塩｝",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 146, name: "Lithium",                 creator: "L4tezk",                list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 147, name: "Keres",                   creator: "ItsHybrid",             list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 148, name: "IRIS",                    creator: "[COMET] Kaza",          list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 149, name: "Galeforce",               creator: "OniLink",               list: "extended", difficulty: "Extreme Demon", featured: false },
  { rank: 150, name: "Cold Sweat",              creator: "para",                  list: "extended", difficulty: "Extreme Demon", featured: false },
];
