// Geometry Dash Demon List
// Based on pointercrate.com/demonlist
// Custom: Ton 618 = #1, Thinking Space II = #2

const DEMONS = [
  // ── MAIN LIST (1–75) ──────────────────────────────────────
  { rank: 1,   name: "Ton 618",               creator: "Arctic and Pooch",           list: "main" },
  { rank: 2,   name: "Thinking Space II",      creator: "Atomic",         list: "main" },
  { rank: 3,   name: "Tidal Wave",             creator: "OniLink",        list: "main" },
  { rank: 4,   name: "Nullscapes",             creator: "Kiba",           list: "main" },
  { rank: 5,   name: "Avernus",                creator: "PockeWindfish",  list: "main" },
  { rank: 6,   name: "Anathema",               creator: "nikrodox",       list: "main" },
  { rank: 7,   name: "Acheron",                creator: "ryamu",          list: "main" },
  { rank: 8,   name: "Silent Clubstep",        creator: "Sailent",        list: "main" },
  { rank: 9,   name: "Spectre",                creator: "xander",         list: "main" },
  { rank: 10,  name: "Tunnel of Despair",      creator: "Exen",           list: "main" },
  { rank: 11,  name: "Abyss of Darkness",      creator: "Exen",           list: "main" },
  { rank: 12,  name: "Kyouki",                 creator: "Demishio",       list: "main" },
  { rank: 13,  name: "BOOBAWAMBA",             creator: "akun akun",      list: "main" },
  { rank: 14,  name: "Slaughterhouse",         creator: "icedcave",       list: "main" },
  { rank: 15,  name: "Sakupen Circles",        creator: "Diamond",        list: "main" },
  { rank: 16,  name: "KOCMOC",                 creator: "Cherry Team",    list: "main" },
  { rank: 17,  name: "Menace",                 creator: "MannyHeffley",   list: "main" },
  { rank: 18,  name: "Deimos",                 creator: "ItsHybrid",      list: "main" },
  { rank: 19,  name: "Firework",               creator: "Trick",          list: "main" },
  { rank: 20,  name: "The Lightning Rod",      creator: "Lavatrex",       list: "main" },
  { rank: 21,  name: "poocubed",               creator: "Lisp",           list: "main" },
  { rank: 22,  name: "KOSETSU",                creator: "fwe",            list: "main" },
  { rank: 23,  name: "Saul Goodman",           creator: "Renn241",        list: "main" },
  { rank: 24,  name: "Eyes in the Water",      creator: "hawkyre",        list: "main" },
  { rank: 25,  name: "MINUSdry",               creator: "CDMusic",        list: "main" },
  { rank: 26,  name: "Solar Flare",            creator: "Linear",         list: "main" },
  { rank: 27,  name: "Belladonna",             creator: "Cherry Team",    list: "main" },
  { rank: 28,  name: "The Hallucination",      creator: "SyQual",         list: "main" },
  { rank: 29,  name: "COMBUSTION",             creator: "Cersia",         list: "main" },
  { rank: 30,  name: "LIMBO",                  creator: "MindCap",        list: "main" },
  { rank: 31,  name: "Edge of Destiny",        creator: "CDMusic",        list: "main" },
  { rank: 32,  name: "Codependence",           creator: "TCTeam",         list: "main" },
  { rank: 33,  name: "Mayhem",                 creator: "LordVadercraft", list: "main" },
  { rank: 34,  name: "walter white",           creator: "Renn241",        list: "main" },
  { rank: 35,  name: "Deadlier Clubstep",      creator: "HeroZombie80",   list: "main" },
  { rank: 36,  name: "PSYCHOPATH",             creator: "DeniPol",        list: "main" },
  { rank: 37,  name: "The Yangire",            creator: "Dorami",         list: "main" },
  { rank: 38,  name: "SARYYX NEVER CLEAR",     creator: "artos",          list: "main" },
  { rank: 39,  name: "Collapse",               creator: "Nexel",          list: "main" },
  { rank: 40,  name: "The Plunge",             creator: "Dolabill",       list: "main" },
  { rank: 41,  name: "Midnight",               creator: "Yuko",           list: "main" },
  { rank: 42,  name: "Sinister Silence",       creator: "Wahffle",        list: "main" },
  { rank: 43,  name: "arcturus",               creator: "maxfs",          list: "main" },
  { rank: 44,  name: "UNKNOWN",                creator: "NineDice",       list: "main" },
  { rank: 45,  name: "BEELINE",                creator: "Waffl3x",        list: "main" },
  { rank: 46,  name: "Sonic Wave Infinity",    creator: "APTeam",         list: "main" },
  { rank: 47,  name: "Damascus",               creator: "Dzeser",         list: "main" },
  { rank: 48,  name: "Waterfall",              creator: "Cherry Team",    list: "main" },
  { rank: 49,  name: "BPATA MPAKA",            creator: "Inex",           list: "main" },
  { rank: 50,  name: "Tartarus",               creator: "Dolphy",         list: "main" },
  { rank: 51,  name: "Jigsaw",                 creator: "NekonGames",     list: "main" },
  { rank: 52,  name: "Oblivion",               creator: "dice88",         list: "main" },
  { rank: 53,  name: "Viprin UFO",             creator: "hawkyre",        list: "main" },
  { rank: 54,  name: "Coalescence",            creator: "Amplitron",      list: "main" },
  { rank: 55,  name: "The Golden",             creator: "BoBoBoBoBoBoBo", list: "main" },
  { rank: 56,  name: "Natural Disaster",       creator: "iIiLaSeRiIi",    list: "main" },
  { rank: 57,  name: "Verdant Landscape",      creator: "Nisha",          list: "main" },
  { rank: 58,  name: "Climax",                 creator: "HushLC",         list: "main" },
  { rank: 59,  name: "ORDINARY",               creator: "vit12",          list: "main" },
  { rank: 60,  name: "Delta",                  creator: "Drakosa",        list: "main" },
  { rank: 61,  name: "NETWORK",                creator: "Agat3",          list: "main" },
  { rank: 62,  name: "Shukketsu",              creator: "Yuko",           list: "main" },
  { rank: 63,  name: "Terminal Rampancy",      creator: "Xyriak",         list: "main" },
  { rank: 64,  name: "Critical Heat",          creator: "Zeniux",         list: "main" },
  { rank: 65,  name: "Trueffet",               creator: "SyQual",         list: "main" },
  { rank: 66,  name: "Aerial Gleam",           creator: "EndLevel",       list: "main" },
  { rank: 67,  name: "The Paroxysm of Rage",   creator: "Zacanaii",       list: "main" },
  { rank: 68,  name: "Judgement Knights",      creator: "HangerLord",     list: "main" },
  { rank: 69,  name: "Zodiac",                 creator: "Bianox",         list: "main" },
  { rank: 70,  name: "Kenos",                  creator: "npesta",         list: "main" },
  { rank: 71,  name: "Hard Machine",           creator: "Komp",           list: "main" },
  { rank: 72,  name: "Esfera",                 creator: "SyQual",         list: "main" },
  { rank: 73,  name: "Destruction 19",         creator: "bosjoker",       list: "main" },
  { rank: 74,  name: "Checked Steam",          creator: "gruzy",          list: "main" },
  { rank: 75,  name: "NEUTRA",                 creator: "Jenkins GD",     list: "main" },

  // ── EXTENDED LIST (76–150) ────────────────────────────────
  { rank: 76,  name: "DISSONANCE",             creator: "ImMaxX1",        list: "extended" },
  { rank: 77,  name: "Scream Machine",         creator: "TMco",           list: "extended" },
  { rank: 78,  name: "Keres",                  creator: "ItsHybrid",      list: "extended" },
  { rank: 79,  name: "Ascent",                 creator: "Rimexon",        list: "extended" },
  { rank: 80,  name: "Fragile",                creator: "EndLevel",       list: "extended" },
  { rank: 81,  name: "Widestep",               creator: "Demishio",       list: "extended" },
  { rank: 82,  name: "Crackhead Circles",      creator: "AlrexX",         list: "extended" },
  { rank: 83,  name: "Lotus Flower",           creator: "StarkyTheSalad", list: "extended" },
  { rank: 84,  name: "Frost Spirit",           creator: "Quavbus",        list: "extended" },
  { rank: 85,  name: "Dry Out Copyable 2",     creator: "tenzk",          list: "extended" },
  { rank: 86,  name: "Axinie",                 creator: "SaturMan",       list: "extended" },
  { rank: 87,  name: "Promethean",             creator: "EndLevel",       list: "extended" },
  { rank: 88,  name: "Cold Sweat",             creator: "para",           list: "extended" },
  { rank: 89,  name: "Thinking Space",         creator: "Atomic",         list: "extended" },
  { rank: 90,  name: "qoUEO",                  creator: "GhostVandalf",   list: "extended" },
  { rank: 91,  name: "Renevant",               creator: "nikrodox",       list: "extended" },
  { rank: 92,  name: "SUPERHATEMEWORLD",       creator: "icedcave",       list: "extended" },
  { rank: 93,  name: "Lithium",                creator: "L4tezk",         list: "extended" },
  { rank: 94,  name: "ConClusion",             creator: "DreamZoneGD",    list: "extended" },
  { rank: 95,  name: "Instinct",               creator: "Krazyman50Real", list: "extended" },
  { rank: 96,  name: "Sky Shredder",           creator: "Dorvict",        list: "extended" },
  { rank: 97,  name: "Calculator Core",        creator: "Walroose",       list: "extended" },
  { rank: 98,  name: "Trotil",                 creator: "Cherry Team",    list: "extended" },
  { rank: 99,  name: "shimmer",                creator: "Amplitron",      list: "extended" },
  { rank: 100, name: "Crimson Planet",         creator: "TrueOmega",      list: "extended" },
  { rank: 101, name: "DIRECTIONS",             creator: "ryli",           list: "extended" },
  { rank: 102, name: "Cognition",              creator: "EndLevel",       list: "extended" },
  { rank: 103, name: "Cosmic Cyclone",         creator: "APTeam",         list: "extended" },
  { rank: 104, name: "Guideless Goobering",    creator: "Enfur",          list: "extended" },
  { rank: 105, name: "SARY NEVER CLEAR",       creator: "KugelBlitZ",     list: "extended" },
  { rank: 106, name: "Rigel",                  creator: "Dan2D",          list: "extended" },
  { rank: 107, name: "Ykds1479ymdppr",         creator: "Kapycta999",     list: "extended" },
  { rank: 108, name: "Akashic Records",        creator: "VoTcHi",         list: "extended" },
  { rank: 109, name: "RUST",                   creator: "neigefeu",       list: "extended" },
  { rank: 110, name: "CORRODERE",              creator: "Moosh",          list: "extended" },
  { rank: 111, name: "Launchpad Labyrinth",    creator: "Moffe",          list: "extended" },
  { rank: 112, name: "Lucid Nightmares",       creator: "CairoX",         list: "extended" },
  { rank: 113, name: "Cobwebs",                creator: "NineDice",       list: "extended" },
  { rank: 114, name: "Coral Cave",             creator: "awesomeme360",   list: "extended" },
  { rank: 115, name: "Shardscapes",            creator: "Kiba",           list: "extended" },
  { rank: 116, name: "Amalgam",                creator: "XLSpiral",       list: "extended" },
  { rank: 117, name: "Indivine",               creator: "MercuryDT",      list: "extended" },
  { rank: 118, name: "RUTHLESS",               creator: "Surjaco",        list: "extended" },
  { rank: 119, name: "Sides Of My Mind",       creator: "MaxxoRMeN",      list: "extended" },
  { rank: 120, name: "Horros",                 creator: "Shrc",           list: "extended" },
  { rank: 121, name: "Omega Interface",        creator: "Platnuu",        list: "extended" },
  { rank: 122, name: "Escape Room",            creator: "SleyGD",         list: "extended" },
  { rank: 123, name: "Ragnarok",               creator: "knobbelboy",     list: "extended" },
  { rank: 124, name: "TORN",                   creator: "Kyhros",         list: "extended" },
  { rank: 125, name: "me when machine gang",   creator: "akun akun",      list: "extended" },
  { rank: 126, name: "Silent Club",            creator: "Luqualizer",     list: "extended" },
  { rank: 127, name: "SAND SAILOR",            creator: "Custi",          list: "extended" },
  { rank: 128, name: "Pandemonium",            creator: "Cersia",         list: "extended" },
  { rank: 129, name: "Descent Into Exile",     creator: "GrenadeofTacos", list: "extended" },
  { rank: 130, name: "Neon Skyline",           creator: "recillia",       list: "extended" },
  { rank: 131, name: "The Rupture",            creator: "Ka1ns",          list: "extended" },
  { rank: 132, name: "Scrubbabingo force",     creator: "akun akun",      list: "extended" },
  { rank: 133, name: "Jupiter My Favourite",   creator: "akun akun",      list: "extended" },
  { rank: 134, name: "The Art of the Blade",   creator: "mbed",           list: "extended" },
  { rank: 135, name: "Kappa",                  creator: "Armadeus",       list: "extended" },
  { rank: 136, name: "no jokes",               creator: "TheParadoxTeam", list: "extended" },
  { rank: 137, name: "LD50",                   creator: "StarkytheSalad", list: "extended" },
  { rank: 138, name: "Nabil Let Go",           creator: "Nab",            list: "extended" },
  { rank: 139, name: "Bloodlust",              creator: "knobbelboy",     list: "extended" },
  { rank: 140, name: "Asterios",               creator: "Exen",           list: "extended" },
  { rank: 141, name: "Excruciation Chamber",   creator: "spcreat",        list: "extended" },
  { rank: 142, name: "PROTON LAUNCHER",        creator: "MultiverseGD",   list: "extended" },
  { rank: 143, name: "Jesse Pinkman",          creator: "Renn241",        list: "extended" },
  { rank: 144, name: "Terminux",               creator: "VulgarisAerae",  list: "extended" },
  { rank: 145, name: "BarbarosFinaleFinale",   creator: "awesomeme360",   list: "extended" },
  { rank: 146, name: "Twilight",               creator: "Yuko",           list: "extended" },
  { rank: 147, name: "CITRA",                  creator: "Varse",          list: "extended" },
  { rank: 148, name: "Awedsy",                 creator: "sink",           list: "extended" },
  { rank: 149, name: "Fog",                    creator: "notesxd",        list: "extended" },
  { rank: 150, name: "DISSONANCE II",          creator: "ImMaxX1",        list: "extended" },
];
